### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by Yagun** [avoroshilov/neural-style#2]
I like your project and the example pictures are impressive.

Please tell me what parameters did you use to get those blue cats pictures from the brown cat source. I tried different combinations of parameters, but the pictures have lots of brown and orange in addition to blue. The cat ears, for example, always stay brown.

I changed --content-weight from 5 to 0.05, --style-weight from 500 to 50000, --content-weight-blend from 0.5 to 1. And also tried --ashift.

But the resulting cat painting colors are not similar to your examples.

Please also tell some working parameters for the SQZ network. Because it transfers the colors, but does not transfer the texture.

Thanks.

**Comment by avoroshilov** [comment]
Hello! Thank you for the kind words.
This was quite a while ago, so I don't remember the exact parameters that I generated those images with, but I have a script lying around which basically boils down to this line:
```
python neural_style.py --content "cat.png" --styles "s10_starryNight_cropped2.jpg" --style-feat-type gram --network-type vgg --initial-noiseblend 0.1 --style-layer-weight-exp 0.5 --style-weight 1e4 --content-weight-blend 0.1 --pooling avg --iterations 200 --optim lbfgs --max-hierarchy 3 --ashift 150 --tv-weight 2  --style-distr-weight 1.6e3
```

which produces the following image:
![t_cat png_s10_starrynight_cropped2 jpg_lbfgs0200_h3_pavg_sw10000_sdw16e2_swe05_cwe01_as150_vgg_](https://user-images.githubusercontent.com/11299031/35195316-b695567a-fed2-11e7-80e9-8d5cd18f2b32.jpg)

Hope this helps! I will look up SqueezeNet parameters a little bit later.

**Comment by avoroshilov** [comment]
For SqueezeNet, I am getting somewhat tolerable results with similar line:
```
python neural_style.py --content "cat.png" --styles "s10_starryNight_cropped2.jpg" --style-feat-type gram --network-type sqz --initial-noiseblend 0.1 --style-layer-weight-exp 0.5 --style-weight 1e3 --content-weight-blend 0.1 --pooling avg --iterations 200 --optim lbfgs --max-hierarchy 3 --ashift 150 --tv-weight 2  --style-distr-weight 1.6e2
```
this yields the following image:
![t_cat png_s10_starrynight_cropped2 jpg_lbfgs0200_h3_pavg_sw01000_sdw01e2_swe05_cwe01_as150_sqz_](https://user-images.githubusercontent.com/11299031/35195550-4c1b2a1e-fed6-11e7-8cd6-2851449cbeb5.jpg)

I didn't put too much effort into tweaking the result, but I think you could go from here. Please note however, that SqueezeNet generally produces worse results than VGG, but is a little better in terms of performance. So I wouldn't recommend SQZ backend, unless it is absolutely necessary.

**Comment by Yagun** [comment]
Thank you for your prompt answer. These parameters produce more similar results, definitely.

I used your parameters, with only difference: Adam optimizer. I will try to fix 2 other optimizers and test with them.

VGG:

![result_vgg_author_parameters](https://user-images.githubusercontent.com/34515418/35197260-cd73cbf4-fed4-11e7-9792-dd17a1a7911d.jpg)

SQZ:

![result_sqz_author_parameters](https://user-images.githubusercontent.com/34515418/35197265-d820ad88-fed4-11e7-94df-bf848b65b37c.jpg)

This is what it used to be before (I told about brown color):

![result_cat_to_github](https://user-images.githubusercontent.com/34515418/35197279-f7d7e498-fed4-11e7-9f6b-bcc4772c478a.jpg)

**Comment by avoroshilov** [comment]
Well, Adam typically converges slower than L-BFGS, so you could try increasing number of iterations in case you see artifacts.
